# Generated by Django 4.2.6 on 2024-05-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=20)),
                ('nombreCompleto', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
    ]
